# Generated by Django 5.2.9 on 2025-12-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mood', models.CharField(choices=[('very_happy', 'Very Happy'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('stressed', 'Stressed'), ('sad', 'Sad'), ('very_sad', 'Ver Sad')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
